import { t } from '@rawgraphs/rawgraphs-core'

export const visualOptions = {
  marginTop: {
    type: 'number',
    label: t('visualOptions.marginTop'),
    default: 50,
    group: 'artboard',
  },
  marginRight: {
    type: 'number',
    label: t('visualOptions.marginRight'),
    default: 50,
    group: 'artboard',
  },
  marginBottom: {
    type: 'number',
    label: t('visualOptions.marginBottom'),
    default: 50,
    group: 'artboard',
  },
  marginLeft: {
    type: 'number',
    label: t('visualOptions.marginLeft'),
    default: 50,
    group: 'artboard',
  },
  showLegend: {
    type: 'boolean',
    label: t('visualOptions.showLegend'),
    default: false,
    group: 'artboard',
    requiredDimensions: ['x', 'y', 'group'],
  },
  legendWidth: {
    type: 'number',
    label: t('visualOptions.legendWidth'),
    default: 200,
    group: 'artboard',
    disabled: {
      showLegend: false,
    },
    container: 'width',
    containerCondition: {
      showLegend: true,
    },
  },
  xOrigin: {
    type: 'boolean',
    label: t('visualOptions.xOrigin'),
    default: false,
    group: 'chart',
    requiredDimensions: ['x', 'y'],
  },
  yOrigin: {
    type: 'boolean',
    label: t('visualOptions.yOrigin'),
    default: false,
    group: 'chart',
    requiredDimensions: ['x', 'y'],
  },
  groupStrokeWidth: {
    type: 'number',
    label: t('visualOptions.groupStrokeWidth'),
    default: 10,
    step: 1,
    min: 1,
    group: 'chart',
    requiredDimensions: ['x', 'y'],
  },
  groupOpacity: {
    type: 'number',
    label: t('visualOptions.groupOpacity'),
    default: 0.5,
    step: 0.1,
    min: 0,
    max: 1,
    group: 'chart',
    requiredDimensions: ['x', 'y'],
  },
  showPoints: {
    type: 'boolean',
    label: t('visualOptions.showDotsOnData'),
    default: true,
    group: 'chart',
    requiredDimensions: ['x', 'y'],
  },
  dotsDiameter: {
    type: 'number',
    label: t('visualOptions.dotsDiameter'),
    default: 2,
    group: 'chart',
    disabled: {
      showPoints: false,
    },
    requiredDimensions: ['x', 'y'],
  },
  colorScale: {
    type: 'colorScale',
    label: t('visualOptions.colorScale'),
    dimension: 'group',
    default: {
      scaleType: 'ordinal',
      interpolator: 'interpolateSpectral',
    },
    group: 'colors',
    requiredDimensions: ['x', 'y'],
  },
  labelStyles: {
    type: 'text',
    label: t('visualOptions.labelStyles'),
    group: 'labels',
    options: [
      {
        label: t('visualOptions.labelStylesOptions.labelPrimary'),
        value: 'labelPrimary',
      },
      {
        label: t('visualOptions.labelStylesOptions.labelSecondary'),
        value: 'labelSecondary',
      },
      {
        label: t('visualOptions.labelStylesOptions.labelItalic'),
        value: 'labelItalic',
      },
    ],
    default: 'labelPrimary',
    repeatFor: 'label',
    repeatDefault: ['labelPrimary', 'labelSecondary', 'labelItalic'],
    requiredDimensions: ['x', 'y', 'label'],
  },
  showLabelsOutline: {
    type: 'boolean',
    label: t('visualOptions.showLabelsOutline'),
    default: false,
    group: 'labels',
    requiredDimensions: ['x', 'y', 'label'],
  },
  autoHideLabels: {
    type: 'boolean',
    label: t('visualOptions.autoHideLabels'),
    default: false,
    group: 'labels',
    requiredDimensions: ['x', 'y', 'label'],
  },
}
