export { default as scatterplot } from './scatterplot'
export { default as linechart } from './linechart'
export { default as colortest } from './colortest'
export { default as matrixplot } from './matrixplot'
export { default as sunburst } from './sunburst'
export { default as sankeydiagram } from './sankeydiagram'
export { default as alluvialdiagram } from './alluvialdiagram'
export { default as beeswarm } from './beeswarm'
